quarkus:
  kafka-streams:
    application-id: turtlebots4
    topics: in_1,out_1

"%dev":
  quarkus:
    kafka-streams:
      schema-registry-url: http://localhost:8081
      bootstrap-servers: localhost:9092

"%prod":
  quarkus:
    kafka-streams:
      bootstrap-servers: 141.28.73.94:9092
      schema-registry-url: http://141.28.73.94:8081
